name: Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install apt dependencies
        run: sudo apt-get install bcftools
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Test
        run: pytest -svv --cov=bento_variant_service --cov-branch
      - name: Codecov
        run: codecov
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bento_variant_service
        run: python -m pip install .
